[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "morphx"
version = "1.0.1"
description = "Универсальный преобразователь данных: dict → Model → DataFrame → JSON → CSV"
readme = "README.md"
requires-python = ">=3.9"

authors = [
    { name = "busyaaa_1" }
]

dependencies = [
    "pydantic>=2.0",
    "pandas>=1.5"
]

[project.urls]
Homepage = "https://github.com/busyaaa1/morphx"

[tool.hatch.build.targets.wheel]
packages = ["morphx"]